modified

diff --git a/SaaSContainerBasedWorkflowRockyLinux b/SaaSContainerBasedWorkflowRockyLinux
--- a/SaaSContainerBasedWorkflowRockyLinux
+++ b/SaaSContainerBasedWorkflowRockyLinux
@@ -2,228 +2,227 @@ def gv
 def emailHandle
 def buildDir
 def stageDir
-def BUILD_AGENT='SAAS_di2inpun2630lv0_yytwint'
-def TEST_AGENT='SAAS_di2inpun2631lv0_yytwint'
-def STAGE_AGENT='SAAS_di2inpun2631lv0_yytwint'
+def BUILD_AGENT = 'SAAS_di2inpun2630lv0_yytwint'
+def TEST_AGENT = 'SAAS_di2inpun2631lv0_yytwint'
+def STAGE_AGENT = 'SAAS_di2inpun2631lv0_yytwint'
 def boolean anyFailure = false
 
 pipeline {
     agent any
-	parameters {
-		string(name: 'NXRelease', defaultValue: 'nx2412.latest', description : 'Use the latest IP from NX2412 release to create the build.')
-		booleanParam(name: 'SeriesBuild', defaultValue: false, description : 'Enable SeriesRelease when Series release build is required ')
-		string(name: 'SeriesName', defaultValue: '0', description : 'Provide the Series name for which you want to build the pipeline. series name format should be like  "NX2412_Series.3000".')
-		string(name: 'UnitPath', defaultValue: '/apps/JenkinsBase/units/Dev', description : 'Path where build unit for the run is to be created.')
-		string(name: 'StagePath', defaultValue: '/apps/JenkinsBase/stage/Dev', description : 'Path where translator worker kits are to be staged.')
-		booleanParam(name: 'HC', defaultValue: false, description : 'Enable horizontal collaboration change package ')
-		string(name: 'CPNumber', defaultValue: '0', description : 'CP number on top of NXRelease against which build and test steps to be executed.')
-		booleanParam(name: 'Deploy', defaultValue: false, description : 'Deploy staging directory contents to customer setup')
-	}
+    parameters {
+        string(name: 'NXRelease', defaultValue: 'nx2412.latest', description: 'Use the latest IP from NX2412 release to create the build.')
+        booleanParam(name: 'SeriesBuild', defaultValue: false, description: 'Enable SeriesRelease when Series release build is required ')
+        string(name: 'SeriesName', defaultValue: '0', description: 'Provide the Series name for which you want to build the pipeline. series name format should be like "NX2412_Series.3000".')
+        string(name: 'UnitPath', defaultValue: '/apps/JenkinsBase/units/Dev', description: 'Path where build unit for the run is to be created.')
+        string(name: 'StagePath', defaultValue: '/apps/JenkinsBase/stage/Dev', description: 'Path where translator worker kits are to be staged.')
+        booleanParam(name: 'HC', defaultValue: false, description: 'Enable horizontal collaboration change package ')
+        string(name: 'CPNumber', defaultValue: '0', description: 'CP number on top of NXRelease against which build and test steps to be executed.')
+        booleanParam(name: 'Deploy', defaultValue: false, description: 'Deploy staging directory contents to customer setup')
+    }
     stages {
-		stage ('Init'){
-			steps {
-				script{
-					gv = load "ContainerBasedWorkflow.groovy"
-					emailHandle = load "email.groovy"
-					buildDir="${params.UnitPath}/${params.NXRelease}_TranslatorWorker_${BUILD_TIMESTAMP}"
-					stageDir="${params.StagePath}/${params.NXRelease}_TranslatorWorker_${BUILD_TIMESTAMP}"
-					NXReleaseVersion="${params.NXRelease}"
-					HCFlag="${params.HC}"
-					SeriesFlag="${params.SeriesBuild}"
-				}
-			}
-		}
-		
-		stage('CreateUnit') {
-            agent { label "${BUILD_AGENT}" }
+        stage('Init') {
             steps {
-				script{
-					def CP="${params.CPNumber}"
-					if (("${HCFlag}"=="false") || (("${HCFlag}"=="true") && ("${CP}"!="0"))){
-						if (("${SeriesFlag}"=="false") || (("${SeriesFlag}"=="true") && ("${params.SeriesName}"!="0"))){
-							//gv.CreateUnit(buildDir) 
-							echo 'linux create'
-							BUILD_PROCESS_FLAG=false
-						}
-						else{
-							error "you have selected Series Build option but Series name is not specified correctly so skipping Group build and testing!"
-							BUILD_PROCESS_FLAG=false						
-						}
-					}
-					else {
-						error "you have selected HC option but CP number is not specified correctly so skipping Group build and testing!"
-						BUILD_PROCESS_FLAG=false						
-					}
-				}
+                script {
+                    gv = load "ContainerBasedWorkflow.groovy"
+                    emailHandle = load "email.groovy"
+                    buildDir = "${params.UnitPath}/${params.NXRelease}_TranslatorWorker_${BUILD_TIMESTAMP}"
+                    stageDir = "${params.StagePath}/${params.NXRelease}_TranslatorWorker_${BUILD_TIMESTAMP}"
+                }
             }
         }
+        
+        stage('CreateUnit') {
+            agent { label "${BUILD_AGENT}" }
+            steps {
+                script {
+                    def CP = "${params.CPNumber}"
+                    if (("${params.HC}" == "false") || ("${params.HC}" == "true" && ("${CP}" != "0"))) {
+                        if (("${params.SeriesBuild}" == "false") || ("${params.SeriesBuild}" == "true" && ("${params.SeriesName}" != "0"))) {
+                            echo 'linux create'
+                            BUILD_PROCESS_FLAG = false
+                        } else {
+                            error "You have selected Series Build option but Series name is not specified correctly so skipping Group build and testing!"
+                            BUILD_PROCESS_FLAG = false
+                        }
+                    } else {
+                        error "You have selected HC option but CP number is not specified correctly so skipping Group build and testing!"
+                        BUILD_PROCESS_FLAG = false
+                    }
+                }
+            }
+        }
+        
         stage('BuildUnit') {
             agent { label "${BUILD_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
             steps {
-				script{
-					gv.BuildUnit(buildDir) 
-				}					
+                script {
+                    gv.BuildUnit(buildDir)
+                }
             }
         }
-		stage('TestUnit') {
+        
+        stage('TestUnit') {
             agent { label "${TEST_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
             steps {
-				script{
-					echo "docker test"
-					gv.TestUnit(buildDir) 
-				}					
+                script {
+                    echo "docker test"
+                    gv.TestUnit(buildDir)
+                }
             }
         }
-		stage('StageForContainer') {
+        
+        stage('StageForContainer') {
             agent { label "${STAGE_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
             steps {
-				script{
-					gv.StageForContainer(buildDir,stageDir) 
-				}					
+                script {
+                    gv.StageForContainer(buildDir, stageDir)
+                }
             }
         }
-		stage('CheckLicenseServer') {
+        
+        stage('CheckLicenseServer') {
             agent { label "${STAGE_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
             steps {
-				script{
-					gv.CheckLicenseServer() 
-				}					
+                script {
+                    gv.CheckLicenseServer()
+                }
             }
         }
-		stage('RemoveRunningContainers-Pre') {
+        
+        stage('RemoveRunningContainers-Pre') {
             agent { label "${STAGE_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
             steps {
-				script{
-					gv.RemoveRunningContainers() 
-				}					
+                script {
+                    gv.RemoveRunningContainers()
+                }
             }
         }
-		stage('BuildAndRunDocker') {
+        
+        stage('BuildAndRunDocker') {
             agent { label "${STAGE_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
-            steps {					
-				script{
-					try{
-						gv.BuildAndRunDockerRockyLinux(buildDir,stageDir) 
-					}
-					catch (Exception e) {
-						echo 'Exception occurred: ' + e.toString()
-						anyFailure = true
-					}
-				}			
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
+            steps {
+                script {
+                    try {
+                        gv.BuildAndRunDockerRockyLinux(buildDir, stageDir)
+                    } catch (Exception e) {
+                        echo 'Exception occurred: ' + e.toString()
+                        anyFailure = true
+                    }
+                }
             }
         }
-		stage('DockerCleanup') {
+        
+        stage('DockerCleanup') {
             agent { label "${STAGE_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
-            steps {
-					catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
-					script{
-						gv.DockerCleanup(stageDir) 
-					}
-				}				
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
             }
-        }	
-		stage('RemoveRunningContainers-Post') {
-			agent { label "${STAGE_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
-			steps {
-				script{
-					gv.RemoveRunningContainers() 
-				}					
-			}
-		}
-		stage('DeployContainer') {
-			agent { label "${STAGE_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
-			steps {
-				script{
-					gv.DeployContainer(buildDir,stageDir) 
-				}					
-			}
-		}			
-				
-		stage('Purge Unit') {
-			agent { label "${BUILD_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
-			steps {
-				script{
-					if( anyFailure == false ) {
-						gv.Purge("${params.UnitPath}") 
-					}
-					else {
-						echo "Skipping Purge Unit due to earlier failure"
-					}
-				}					
-			}
-		}
-
-		stage('Purge Stage') {
-			agent { label "${STAGE_AGENT}" }
-			when {
-					expression { "${BUILD_PROCESS_FLAG}"=="true" }
-				}
-			steps {
-				script{
-					if( anyFailure == false ) {
-						gv.Purge("${params.StagePath}") 
-					}
-					else {
-						echo "Skipping Purge Stage due to earlier failure"
-					}
-				}					
-			}
-		}
-		
-		stage('Evaluate Status') {
-			steps{
-				script {
-					if( anyFailure == true ) {
-						currentBuild.result = 'FAILURE'
-						currentBuild.buildResult = 'FAILURE'
-					}
-				}
-			}
-		}
+            steps {
+                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+                    script {
+                        gv.DockerCleanup(stageDir)
+                    }
+                }
+            }
+        }
+        
+        stage('RemoveRunningContainers-Post') {
+            agent { label "${STAGE_AGENT}" }
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
+            steps {
+                script {
+                    gv.RemoveRunningContainers()
+                }
+            }
+        }
+        
+        stage('DeployContainer') {
+            agent { label "${STAGE_AGENT}" }
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
+            steps {
+                script {
+                    gv.DeployContainer(buildDir, stageDir)
+                }
+            }
+        }
+        
+        stage('Purge Unit') {
+            agent { label "${BUILD_AGENT}" }
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
+            steps {
+                script {
+                    if (anyFailure == false) {
+                        gv.Purge("${params.UnitPath}")
+                    } else {
+                        echo "Skipping Purge Unit due to earlier failure"
+                    }
+                }
+            }
+        }
+        
+        stage('Purge Stage') {
+            agent { label "${STAGE_AGENT}" }
+            when {
+                expression { "${BUILD_PROCESS_FLAG}" == "true" }
+            }
+            steps {
+                script {
+                    if (anyFailure == false) {
+                        gv.Purge("${params.StagePath}")
+                    } else {
+                        echo "Skipping Purge Stage due to earlier failure"
+                    }
+                }
+            }
+        }
+        
+        stage('Evaluate Status') {
+            steps {
+                script {
+                    if (anyFailure == true) {
+                        currentBuild.result = 'FAILURE'
+                        currentBuild.buildResult = 'FAILURE'
+                    }
+                }
+            }
+        }
     }
-
+    
     post {
-		
         success {
             echo 'All tasks completed successfully.'
         }
-		failure {
-			echo 'One or more stages have failed.'
-		}	
-		always{
-			script{
-				emailHandle.sendEmail(buildDir,stageDir)
-			}
-		}
+        failure {
+            echo 'One or more stages have failed.'
+        }
+        always {
+            script {
+                emailHandle.sendEmail(buildDir, stageDir)
+            }
+        }
     }
 }
